ALTER TYPE "SupplyChainDesignTableType" ADD VALUE IF NOT EXISTS 'PROVIDER_OPTIONS';
ALTER TYPE "SupplyChainDesignTableType" ADD VALUE IF NOT EXISTS 'SHIPMENT_PROFILES';
ALTER TYPE "SupplyChainDesignTableType" ADD VALUE IF NOT EXISTS 'OUTBOUND_RATE_CACHE';
ALTER TYPE "SupplyChainDesignTableType" ADD VALUE IF NOT EXISTS 'EXPECTED_PROVIDER_RESULTS';
