export const HUNTER_COMPANY_RESEARCH_JOB_TYPE = "HUNTER_COMPANY_DEEP_RESEARCH";
export const HUNTER_OUTREACH_HANDOFF_JOB_TYPE = "HUNTER_OUTREACH_HANDOFF";
export const HUNTER_APOLLO_EXCEPTION_RESOLUTION_JOB_TYPE =
  "HUNTER_APOLLO_EXCEPTION_RESOLUTION";
